# -*- coding: utf-8 -*-
"""[Imersão_Python]_Aula_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/C4rl0s-Ca1N4n/ALURA---Imersao-Python_/blob/main/Aula%202/%5BImers%C3%A3o_Python%5D_Aula_02.ipynb

Aula 2 - Imersão Python_
"""

import pandas as pd

df_principal = pd.read_excel("_Imersão Python - Desafio 2.xlsx", sheet_name="Principal")
df_principal

df_total_acoes = pd.read_excel("_Imersão Python - Desafio 2.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel("_Imersão Python - Desafio 2.xlsx", sheet_name="Ticker")
df_ticker

df_chatgpt = pd.read_excel("_Imersão Python - Desafio 2.xlsx", sheet_name="ChatGPT")
df_chatgpt