# -*- coding: utf-8 -*-
"""[Imersão Python_] Desafio 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBOQw-do69xhKHVKIlHG9xsuejqZrosN
"""

!pip install mplfinance

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import mplfinance as mpf
import yfinance as yf
import plotly.graph_objects as go
from plotly.subplots import make_subplots

dados = yf.download('AAPL', start='2023-01-01', end='2023-12-31')

mpf.plot(dados.head(60), type='candle', figsize = (20,12), volume=True, mav=(7,14), style='starsandstripes')

mpf.plot(dados.head(60), type='candle', figsize = (20,12), volume=True, mav=(7,14), style='classic')

mpf.plot(dados.head(100), type='candle', figsize = (24,15), volume=True, mav=(3,7,14), mavcolors=('black', 'blue', 'cyan'), style='yahoo')